default_env: &default
  adapter: postgresql
  encoding: unicode
  database: s_original

development:
  <<: *default

production:
  <<: *default
  host: dpg-cju47s95mpss73bm7j10-a
  database: s_original_fcev
  username: s_original_fcev_user
  password: WwdVULYLRVvyrUD3CHNAohdytP6rTLFe
